apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: mytardis
spec:
  selector:
    matchLabels:
      app: celery
  replicas: 1
  template:
    metadata:
      labels:
        app: celery
        ver: 0.0.1
    spec:
      containers:
        - name: celery-beat
          image: :[dockerImageFullNameTag]
          imagePullPolicy: Always
          command: ["celery", "--app=tardis.celery.tardis_app", "beat", "--loglevel=INFO"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: settings
              mountPath: /app/tardis/settings.yaml
              subPath: settings.yaml
            - name: var-log
              mountPath: /var/log
          resources:
            requests:
              cpu: 200m
          readinessProbe:
            exec:
              command: ["sh", "-c", "python3 beat.py"]
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "tardis.settings"
            - name: CELERY_APP
              value: "tardis.celery.tardis_app"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Australia/Melbourne
        - name: settings
          configMap:
            name: mytardis
        - name: var-log
          hostPath:
            path: /var/log
