apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: mytardis
spec:
  selector:
    matchLabels:
      app: celery
  replicas: 2
  template:
    metadata:
      labels:
        app: celery
        ver: 0.0.1
    spec:
      containers:
        - name: celery-worker
          image: [dockerImageFullNameTag]
          imagePullPolicy: Always
          command: ["celery", "--app=tardis.celery.tardis_app", "worker", "--queues=celery,default", "--concurrency=1", "--loglevel=INFO"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: settings
              mountPath: /app/tardis/settings.yaml
              subPath: settings.yaml
            - name: var-log
              mountPath: /var/log
            - name: stormon-test-vault
              mountPath: /srv/stormon-test-vault
            - name: smb-stormon-test
              mountPath: /srv/stormon-test
          resources:
            requests:
              cpu: 200m
          readinessProbe:
            exec:
              command: ["sh", "-c", "celery -q --app=tardis.celery.tardis_app inspect -d celery@$(hostname) --timeout=10 ping"]
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "tardis.settings"
            - name: CELERY_APP
              value: "tardis.celery.tardis_app"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Australia/Melbourne
        - name: settings
          configMap:
            name: mytardis
        - name: var-log
          hostPath:
            path: /var/log
        - name: stormon-test-vault
          persistentVolumeClaim:
            claimName: stormon-test-vault
        - name: smb-stormon-test
          persistentVolumeClaim:
            claimName: smb-stormon-test