apiVersion: apps/v1
kind: Deployment
metadata:
  name: download
  namespace: mytardis
spec:
  selector:
    matchLabels:
      app: download
  replicas: 2
  template:
    metadata:
      labels:
        app: download
        ver: 0.0.1
    spec:
      containers:
        - name: download
          image: :[dockerImageFullNameTag]
          imagePullPolicy: Always
          command:
            - gunicorn
            - wsgi:application
            - --bind=:8000
            - --workers=3
            - --worker-class=gevent
            - --timeout=600
            - --log-level=error
            - --log-file=-
            - --worker-tmp-dir=/dev/shm
          env:
            - name: MYTARDIS_VERSION
              valueFrom:
                configMapKeyRef:
                  name: version
                  key: version
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: sentry_dsn
                  name: mytardis
          securityContext:
            privileged: true
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: settings
              mountPath: /app/tardis/settings.yaml
              subPath: settings.yaml
            - name: var-log
              mountPath: /var/log
            - mountPath: /srv/static
              name: nfs-static
            - mountPath: /srv/stormon-staging
              name: smb-staging-storage
            - mountPath: /srv/stormon_ceph
              name: smb-stormon-ceph
            - mountPath: /srv/cryoem
              name: smb-cryoem-ceph
            - mountPath: /srv/xmfig_ceph
              name: smb-xmfig-ceph
            - mountPath: /srv/flowcore_ceph
              name: smb-flowcore-ceph
            - mountPath: /srv/mbi_ceph
              name: smb-mbi-ceph
            - mountPath: /srv/mmi_ceph
              name: smb-mmi-ceph
            - mountPath: /srv/lattice_vault2
              name: smb-lattice-vault2
            - mountPath: /srv/mcem_vault2
              name: smb-mcem-vault2
            - mountPath: /srv/cryoem_vault2
              name: smb-cryoem-vault2
            - mountPath: /srv/cryoem_m1
              name: smb-cryoem-m1-vault2
            - mountPath: /srv/stormon_vault2
              name: smb-stormon-vault2
            - mountPath: /srv/xmfig_vault2
              name: smb-xmfig-vault2
            - mountPath: /srv/mips_cryoem
              name: smb-cryoem-mips-vault2
            - mountPath: /srv/mmi_vault2
              name: smb-mmi-vault2
            - mountPath: /srv/ny79_vault2
              name: smb-ny79-vault2
            - mountPath: /srv/sf32_vault2
              name: smb-sf32-vault2
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Australia/Melbourne
        - name: settings
          configMap:
            name: mytardis
        - name: var-log
          hostPath:
            path: /var/log
        - name: nfs-static
          persistentVolumeClaim:
            claimName: nfs-static
        - name: smb-staging-storage
          persistentVolumeClaim:
            claimName: smb-staging-storage
        - name: smb-stormon-ceph
          persistentVolumeClaim:
            claimName: smb-stormon-ceph
        - name: smb-cryoem-ceph
          persistentVolumeClaim:
            claimName: smb-cryoem-ceph
        - name: smb-xmfig-ceph
          persistentVolumeClaim:
            claimName: smb-xmfig-ceph
        - name: smb-flowcore-ceph
          persistentVolumeClaim:
            claimName: smb-flowcore-ceph
        - name: smb-mbi-ceph
          persistentVolumeClaim:
            claimName: smb-mbi-ceph
        - name: smb-mmi-ceph
          persistentVolumeClaim:
            claimName: smb-mmi-ceph
        - name: smb-lattice-vault2
          persistentVolumeClaim:
            claimName: smb-lattice-vault2
        - name: smb-mcem-vault2
          persistentVolumeClaim:
            claimName: smb-mcem-vault2
        - name: smb-cryoem-vault2
          persistentVolumeClaim:
            claimName: smb-cryoem-vault2
        - name: smb-cryoem-m1-vault2
          persistentVolumeClaim:
            claimName: smb-cryoem-m1-vault2
        - name: smb-stormon-vault2
          persistentVolumeClaim:
            claimName: smb-stormon-vault2
        - name: smb-xmfig-vault2
          persistentVolumeClaim:
            claimName: smb-xmfig-vault2
        - name: smb-cryoem-mips-vault2
          persistentVolumeClaim:
            claimName: smb-cryoem-mips-vault2
        - name: smb-mmi-vault2
          persistentVolumeClaim:
            claimName: smb-mmi-vault2
        - name: smb-ny79-vault2
          persistentVolumeClaim:
            claimName: smb-ny79-vault2
        - name: smb-sf32-vault2
          persistentVolumeClaim:
            claimName: smb-sf32-vault2