apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  namespace: mytardis
spec:
  selector:
    matchLabels:
      app: sftp
  replicas: 2
  template:
    metadata:
      labels:
        app: sftp
        ver: 0.0.1
    spec:
      containers:
        - name: sftp
          image: :[dockerImageFullNameTag]
          imagePullPolicy: Always
          command: ["python3", "manage.py", "sftpd", "-H", "0.0.0.0"]
          securityContext:
            privileged: true
          ports:
            - name: sftp
              containerPort: 2200
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/localtime
              name: tz-config
            - mountPath: /app/tardis/settings.yaml
              name: settings
              subPath: settings.yaml
            - mountPath: /var/log
              name: var-log
            - mountPath: /srv/static
              name: nfs-static
            - mountPath: /srv/stormon-staging
              name: smb-staging-storage
            - mountPath: /srv/stormon_ceph
              name: smb-stormon-ceph
            - mountPath: /srv/cryoem
              name: smb-cryoem-ceph
            - mountPath: /srv/xmfig_ceph
              name: smb-xmfig-ceph
            - mountPath: /srv/flowcore_ceph
              name: smb-flowcore-ceph
            - mountPath: /srv/mbi_ceph
              name: smb-mbi-ceph
            - mountPath: /srv/mmi_ceph
              name: smb-mmi-ceph
            - mountPath: /srv/lattice_vault2
              name: smb-lattice-vault2
            - mountPath: /srv/mcem_vault2
              name: smb-mcem-vault2
            - mountPath: /srv/cryoem_vault2
              name: smb-cryoem-vault2
            - mountPath: /srv/cryoem_m1
              name: smb-cryoem-m1-vault2
            - mountPath: /srv/stormon_vault2
              name: smb-stormon-vault2
            - mountPath: /srv/xmfig_vault2
              name: smb-xmfig-vault2
            - mountPath: /srv/mips_cryoem
              name: smb-cryoem-mips-vault2
            - mountPath: /srv/mmi_vault2
              name: smb-mmi-vault2
            - mountPath: /srv/ny79_vault2
              name: smb-ny79-vault2
            - mountPath: /srv/sf32_vault2
              name: smb-sf32-vault2
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Australia/Melbourne
          name: tz-config
        - configMap:
            defaultMode: 420
            name: mytardis
          name: settings
        - hostPath:
            path: /var/log
          name: var-log
        - name: nfs-static
          persistentVolumeClaim:
            claimName: nfs-static
        - name: smb-staging-storage
          persistentVolumeClaim:
            claimName: smb-staging-storage
        - name: smb-stormon-ceph
          persistentVolumeClaim:
            claimName: smb-stormon-ceph
        - name: smb-cryoem-ceph
          persistentVolumeClaim:
            claimName: smb-cryoem-ceph
        - name: smb-xmfig-ceph
          persistentVolumeClaim:
            claimName: smb-xmfig-ceph
        - name: smb-flowcore-ceph
          persistentVolumeClaim:
            claimName: smb-flowcore-ceph
        - name: smb-mbi-ceph
          persistentVolumeClaim:
            claimName: smb-mbi-ceph
        - name: smb-mmi-ceph
          persistentVolumeClaim:
            claimName: smb-mmi-ceph
        - name: smb-lattice-vault2
          persistentVolumeClaim:
            claimName: smb-lattice-vault2
        - name: smb-mcem-vault2
          persistentVolumeClaim:
            claimName: smb-mcem-vault2
        - name: smb-cryoem-vault2
          persistentVolumeClaim:
            claimName: smb-cryoem-vault2
        - name: smb-cryoem-m1-vault2
          persistentVolumeClaim:
            claimName: smb-cryoem-m1-vault2
        - name: smb-stormon-vault2
          persistentVolumeClaim:
            claimName: smb-stormon-vault2
        - name: smb-xmfig-vault2
          persistentVolumeClaim:
            claimName: smb-xmfig-vault2
        - name: smb-cryoem-mips-vault2
          persistentVolumeClaim:
            claimName: smb-cryoem-mips-vault2
        - name: smb-mmi-vault2
          persistentVolumeClaim:
            claimName: smb-mmi-vault2
        - name: smb-ny79-vault2
          persistentVolumeClaim:
            claimName: smb-ny79-vault2
        - name: smb-sf32-vault2
          persistentVolumeClaim:
            claimName: smb-sf32-vault2
