apiVersion: batch/v1
kind: Job
metadata:
  name: collectstatic
  namespace: mytardis
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: go
        image: mytardis/k8s-mytardis:latest
        command: ["/bin/sh", "-c", "python manage.py collectstatic --noinput"]
        volumeMounts:
          - name: settings
            mountPath: /app/tardis/settings.yaml
            subPath: settings.yaml
      restartPolicy: Never
      volumes:
      - name: settings
        configMap:
          name: mytardis
